
/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*******************************************************************************/


// Thu Vien
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include "system_stm32f4xx.h"
#include "timer.h"
#include "button.h"
#include "led.h"
#include "melody.h"
#include "Ucglib.h"
#include "temhumsensor.h"
#include "lightsensor.h"
#include "eventbutton.h"
#include "melody.h"
#include "eventman.h"
#include "uartcmd.h"
#include "serial.h"

//Doi ten kieu liet ke
typedef enum{
	EVENT_EMPTY, EVENT_APP_INIT, EVENT_APP_FLUSHMEM_READY
}event_api_t, *event_api_p;

typedef enum{
	STATE_APP_STARTUP, STATE_APP_IDLE, STATE_APP_RESET
}state_app_t;

//Khai bao bien va MACRO
#define CYCLE_SEND_DATA 1000 //ms
#define CMD_ID_LCD								0x87
#define CMD_ID_LED 						 		0x01
#define CMD_TYPE_SET                            0x02
static uint16_t light;
static uint8_t temperature, humidity;
static char src1[20] = "";
static char src2[20] = "";
static char src3[20] = "";
static SSwTimer up_idTimerLightScan = NO_TIMER;
static SSwTimer down_idTimerLightScan = NO_TIMER;
static SSwTimer right_up_idTimerLightScan = NO_TIMER;
static SSwTimer left_down_idTimerLightScan = NO_TIMER;
static SSwTimer task_idMultiSensorScan = NO_TIMER;
static int eCurrentState;
static ucg_t ucg;
static int level = 0;
static int level_1 = 0;
// KHAI BAO HAM
static void Up_multiSensorScan(void *arg);
static void Down_multiSensorScan(void *arg);
void AppInitCommon(void);
static void AppStateManager(uint8_t event);
static void SetStateApp(state_app_t state);
static state_app_t GetStateApp(void);
void LoadConfiguration(void);
void DeviceStateMachine(uint8_t event);
void delay_ms(uint32_t milisecond);
static void Task_multiSensorScan(void *arg);
static void MultiSensorScan(void *arg);
static void Right_Up_LightScan(void *arg);
static void Left_Down_LightScan(void *arg);
void LedCmdSetState(uint8_t led_id, \
		 uint8_t led_color, \
		 uint8_t led_num_blink, \
		 uint8_t led_interval, \
		 uint8_t led_last_state);
void BuzzerCmdSetState(uint8_t buzzer_state);
void LcdCmdSetState(char *text);
void ButtonCmdSetState(uint8_t button_id, uint8_t button_state);

char str[] = "IoT Programming by Lumi Smarthome ";
//HAM MAIN
int main(void)
{
	AppInitCommon();
	SetStateApp(STATE_APP_STARTUP);
	EventSchedulerAdd(EVENT_APP_INIT);
    /* Loop forever */
	while(1)
	{
		processTimerScheduler();
		processEventScheduler();
		processSerialReceiver();
	}
}

//Goi ham co san
void AppInitCommon(void)
{
	SystemCoreClockUpdate();
	TimerInit();
	EventSerial_Init();
	EventSerial_SetEventLedCallback(LedCmdSetState);
	EventSerial_SetEventButtonCallback(ButtonCmdSetState);
	EventSerial_SetEventBuzzerCallback(BuzzerCmdSetState);
	EventSerial_SetEventLcdCallback(LcdCmdSetState);
	EventButton_Init();
	EventSchedulerInit(AppStateManager);
	BuzzerControl_Init();
	LedControl_Init();
	LightSensor_Init(ADC_READ_MODE_DMA);
	TemHumSensor_Init();

	//In ra LCD
	Ucglib4WireSWSPI_begin(&ucg, UCG_FONT_MODE_SOLID);
	ucg_ClearScreen(&ucg);
	ucg_SetFont(&ucg, ucg_font_ncenR12_hr);
	ucg_SetColor(&ucg, 0, 255, 255, 255);
	ucg_SetColor(&ucg, 1, 0, 0, 0);
	ucg_SetRotate180(&ucg);
	LoadConfiguration();

}

//Goi ham su kien
static void AppStateManager(uint8_t event)
{
	switch(GetStateApp())
	{
		case STATE_APP_STARTUP:
			if(event == EVENT_APP_INIT)
			{
				//Load configuration
				LoadConfiguration();
				SetStateApp(STATE_APP_IDLE);
			}
			break;
		case STATE_APP_IDLE:
			{
				DeviceStateMachine(event);
			}
			break;
		case STATE_APP_RESET:
			break;
		default:
			break;
	}
}


static void SetStateApp(state_app_t state)
{
	// Set state of application
	eCurrentState = state;
}

static state_app_t GetStateApp()
{
	//Return state of application
	return eCurrentState;
}

void LedCmdSetState(uint8_t led_id, \
		 uint8_t led_color, \
		 uint8_t led_num_blink, \
		 uint8_t led_interval, \
		 uint8_t led_last_state)
{
		LedControl_SetColorGeneral(led_id, led_color, 0);
		if(led_last_state == 4)
		{
			LedControl_SetColorGeneral(led_id, led_color, 0);
		}
		else if(led_last_state != 4)
		{
			LedControl_SetColorGeneral(led_id, led_color, 50);
		}
}
void BuzzerCmdSetState(uint8_t buzzer_state)
{
	BuzzerControl_SetMelody(danger);
}

void LcdCmdSetState(char *text)
{
	ucg_ClearScreen(&ucg); //xoa man hinh truoc
	ucg_SetFont(&ucg, ucg_font_ncenR14_hr);
	ucg_DrawString(&ucg,15,40,0,text);
}

void ButtonCmdSetState(uint8_t button_id, uint8_t button_state)
{
		//Bat tat led Red
		static bool ledRedState = false;
		// Dao nguoc trang thai LED
		ledRedState = !ledRedState;
		if(button_id == 1 && button_state == 0 && ledRedState)
		{
		    LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_RED, 50);
		    LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_RED, 50);
	        //Gui ban tin cho app
	        LedControl_SendPacketRespond(LED_KIT_ID1, LED_COLOR_RED, 50);
	        LedControl_SendPacketRespond(LED_KIT_ID0, LED_COLOR_RED, 50);
	        //Coi
	        BuzzerControl_SetMelody(pbeep);
	        BuzzerControl_SendPacketRespond(1);
		}
		else if(button_id == 1 && button_state == 0 && ledRedState == 0)
		{
			LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_RED, 0);
			LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_RED, 0);
			//Gui ban tin cho app
			LedControl_SendPacketRespond(LED_KIT_ID1, LED_COLOR_RED, 0);
			LedControl_SendPacketRespond(LED_KIT_ID0, LED_COLOR_RED, 0);
	        //Coi
	        BuzzerControl_SetMelody(pbeep);
	        BuzzerControl_SendPacketRespond(1);
		}
	  	//Bat tat led GREEN
	  	static bool ledGreenState = false;
	    // Dao nguoc trang thai LED
	    ledGreenState = !ledGreenState;
		if(button_id == 2 && button_state == 0 && ledGreenState)
		{
			    LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_GREEN, 50);
			    LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_GREEN, 50);
		        //Gui ban tin cho app
		        LedControl_SendPacketRespond(LED_KIT_ID1, LED_COLOR_GREEN, 50);
		        LedControl_SendPacketRespond(LED_KIT_ID0, LED_COLOR_GREEN, 50);
		        //Coi
		        BuzzerControl_SetMelody(pbeep);
		        BuzzerControl_SendPacketRespond(1);
		}
		else if(button_id == 2 && button_state == 0 && ledGreenState == 0)
		{
			    LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_GREEN, 0);
			    LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_GREEN, 0);
		        //Gui ban tin cho app
		        LedControl_SendPacketRespond(LED_KIT_ID1, LED_COLOR_GREEN, 0);
		        LedControl_SendPacketRespond(LED_KIT_ID0, LED_COLOR_GREEN, 0);
		        //Coi
		        BuzzerControl_SetMelody(pbeep);
		        BuzzerControl_SendPacketRespond(1);
		}

	  	//Bat tat led BLUE
	  	static bool ledBlueState = false;
	    // Dao nguoc trang thai LED
	    ledBlueState = !ledBlueState;
		if(button_id == 4 && button_state == 0 && ledBlueState)
		{
			    LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_BLUE, 50);
			    LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_BLUE, 50);
		        //Gui ban tin cho app
		        LedControl_SendPacketRespond(LED_KIT_ID1, LED_COLOR_BLUE, 50);
		        LedControl_SendPacketRespond(LED_KIT_ID0, LED_COLOR_BLUE, 50);
		        //Coi
		        BuzzerControl_SetMelody(pbeep);
		        BuzzerControl_SendPacketRespond(1);
		}
		else if(button_id == 4 && button_state == 0 && ledBlueState == 0)
		{
			    LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_BLUE, 0);
			    LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_BLUE, 0);
		        //Gui ban tin cho app
		        LedControl_SendPacketRespond(LED_KIT_ID1, LED_COLOR_BLUE, 0);
		        LedControl_SendPacketRespond(LED_KIT_ID0, LED_COLOR_BLUE, 0);
		        //Coi
		        BuzzerControl_SetMelody(pbeep);
		        BuzzerControl_SendPacketRespond(1);
		}
}
//CAU 1: HIEN THI DONG TEXT
void LoadConfiguration(void)
{
	ucg_DrawString(&ucg,50,20,0,"IOT");
	ucg_DrawString(&ucg,15,40,0,"Programming");
//	ucg_DrawString(&ucg,35,60,0,"by Lumi");
//	ucg_DrawString(&ucg,25,80,0,"Smarthome");
	ucg_DrawString(&ucg,55,60,0,"by");
	ucg_DrawString(&ucg,8,80,0,"Vo Quang Vinh");
	Serial_SendPacket(CMD_OPT_NOT_USE,CMD_ID_LCD, CMD_TYPE_SET ,(uint8_t *)str ,strlen(str) - 1 );
}

void DeviceStateMachine(uint8_t event)
{
	switch(event)
	{

		//Nhan nut b3 5 lan
		case EVENT_OF_BUTTON_3_PRESS_5_TIMES:
		{
			//Sau 20 giay HIEN THI CAC THONG SO
			task_idMultiSensorScan = TimerStart("MutilSenSorScan", 15000, 1, MultiSensorScan, NULL);

			//Hien thi LCD
			ucg_ClearScreen(&ucg); //xoa man hinh truoc
			ucg_SetFont(&ucg, ucg_font_ncenR08_hr);
			ucg_DrawString(&ucg,0,10,0,"Device:Board STM32");
			ucg_DrawString(&ucg,0,20,0,"Nucleo");
			ucg_DrawString(&ucg,0,30,0,"Code: STM32F401RE-");
			ucg_DrawString(&ucg,0,40,0,"NUCLEO");
			ucg_DrawString(&ucg,0,50,0,"Manufacturer:");
			ucg_DrawString(&ucg,0,60,0,"STMicroelectronics");
			ucg_DrawString(&ucg,0,70,0,"Kit expansion:");
			ucg_DrawString(&ucg,0,80,0,"Lumi Smarthome");
			ucg_DrawString(&ucg,0,90,0,"Project: Simulator");
			ucg_DrawString(&ucg,0,100,0,"touch switch");
			// LED KIT NHAY 5 LAN
		    for(int i=0;i<5;i++)
			{
		    	LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_GREEN, 50);
				delay_ms(5000);
				LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_RED, 0);
				delay_ms(5000);
			}

		}
		break;
		//CAU 3
		//Nhan nut B1
		case EVENT_OF_BUTTON_1_PRESS_LOGIC:
		{
			//Bat tat led RED
			static bool ledState = false;
		     // Dao nguoc trang thai LED
		      ledState = !ledState;
		      if (ledState)
		      {
		        // Bật LED RED
		        LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_RED, 50);
		        LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_RED, 50);
		        //Gui ban tin cho app
		        LedControl_SendPacketRespond(LED_KIT_ID1, LED_COLOR_RED, 50);
		        LedControl_SendPacketRespond(LED_KIT_ID0, LED_COLOR_RED, 50);
		        //Coi
		        BuzzerControl_SetMelody(pbeep);
		        BuzzerControl_SendPacketRespond(1);
		      }
		      else
		      {
		        // Tắt LED RED
			    LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_RED, 0);
			    LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_RED, 0);
			    //Gui ban tin cho app
			    LedControl_SendPacketRespond(LED_KIT_ID1, LED_COLOR_RED, 0);
			    LedControl_SendPacketRespond(LED_KIT_ID0, LED_COLOR_RED, 0);
			    //Coi
		        BuzzerControl_SetMelody(pbeep);
		        BuzzerControl_SendPacketRespond(1);
		      }
		}	break;
		//Nhan nut B2
		case EVENT_OF_BUTTON_2_PRESS_LOGIC:
		{
			//Bat tat led
			static bool ledState = false;
		     // Dao nguoc trang thai LED
		      ledState = !ledState;
		      if (ledState)
		      {
			        // Bật LED GREEN
			        LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_GREEN, 50);
			        LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_GREEN, 50);

			        //Gui ban tin cho app
			        LedControl_SendPacketRespond(LED_KIT_ID1, LED_COLOR_GREEN, 50);
			        LedControl_SendPacketRespond(LED_KIT_ID0, LED_COLOR_GREEN, 50);
			        //Coi
			        BuzzerControl_SetMelody(pbeep);
			        BuzzerControl_SendPacketRespond(1);
			      }
			      else
			      {
			        // Tắt LED GREEN
				    LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_GREEN, 0);
				    LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_GREEN, 0);

				    //Gui ban tin cho app
				    LedControl_SendPacketRespond(LED_KIT_ID1, LED_COLOR_GREEN, 0);
				    LedControl_SendPacketRespond(LED_KIT_ID0, LED_COLOR_GREEN, 0);
				    //Coi
			        BuzzerControl_SetMelody(pbeep);
			        BuzzerControl_SendPacketRespond(1);
		      }
		}	break;
		//Nhan nut B4
		case EVENT_OF_BUTTON_4_PRESS_LOGIC:
		{
			//Bat tat led
			static bool ledState = false;
		     // Dao nguoc trang thai LED
		      ledState = !ledState;
		      if (ledState)
		      {
			        // Bật LED BLUE
			        LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_BLUE, 50);
			        LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_BLUE, 50);

			        //Gui ban tin cho app
			        LedControl_SendPacketRespond(LED_KIT_ID1, LED_COLOR_BLUE, 50);
			        LedControl_SendPacketRespond(LED_KIT_ID0, LED_COLOR_BLUE, 50);
			        //Coi
			        BuzzerControl_SetMelody(pbeep);
			        BuzzerControl_SendPacketRespond(1);

			      }
			      else
			      {
			        // Tắt LED RED
				    LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_BLUE, 0);
				    LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_BLUE, 0);

				    //Gui ban tin cho app
				    LedControl_SendPacketRespond(LED_KIT_ID1, LED_COLOR_BLUE, 0);
				    LedControl_SendPacketRespond(LED_KIT_ID0, LED_COLOR_BLUE, 0);
				    //Coi
			        BuzzerControl_SetMelody(pbeep);
			        BuzzerControl_SendPacketRespond(1);
		      }
		}	break;
		//Nhan nut B5
		case EVENT_OF_BUTTON_5_PRESS_LOGIC:
		{
			//Bat tat led
			static bool ledState = false;
		     // Dao nguoc trang thai LED
		      ledState = !ledState;
		      if (ledState)
		      {
		        // Bật LED WHITE
		        LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_WHITE, 50);
		        BuzzerControl_SetMelody(pbeep);
		      }
		      else
		      {
		        // Tắt LED WHITE
		        LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_WHITE, 0);
		        BuzzerControl_SetMelody(pbeep);
		      }
		}	break;

		//CAU 4
		//Giu nut B1 1s den tang sang
		case EVENT_OF_BUTTON_1_HOLD_1S:
		{
			if(up_idTimerLightScan != NO_TIMER)
			{
				TimerStop(up_idTimerLightScan);
				up_idTimerLightScan = NO_TIMER;
			}

			up_idTimerLightScan = TimerStart("Up_multiSensorScan", 20, 100, Up_multiSensorScan, NULL);
		}	break;
		//Giu nut B5 1s den giam sang
		case EVENT_OF_BUTTON_5_HOLD_1S:
		{
			if(down_idTimerLightScan != NO_TIMER)
			{
				TimerStop(down_idTimerLightScan);
				down_idTimerLightScan = NO_TIMER;
			}

			down_idTimerLightScan = TimerStart("Down_multiSensorScan", 20, 100, Down_multiSensorScan, NULL);
		}	break;
		//Giu nut B4 1s den tang sang
		case EVENT_OF_BUTTON_4_HOLD_1S:
		{
			if(right_up_idTimerLightScan != NO_TIMER)
			{
				TimerStop(right_up_idTimerLightScan);
				right_up_idTimerLightScan = NO_TIMER;
			}

			right_up_idTimerLightScan = TimerStart("right_up_idTimerLightScan", 20, 100, Right_Up_LightScan, NULL);
		}	break;
		//Giu nut B2 1s den tang sang
		case EVENT_OF_BUTTON_2_HOLD_1S:
		{
			if(left_down_idTimerLightScan != NO_TIMER)
			{
				TimerStop(left_down_idTimerLightScan);
				left_down_idTimerLightScan   = NO_TIMER;
			}

			left_down_idTimerLightScan  = TimerStart("left_down_idTimerLightScan ", 20, 100, Left_Down_LightScan, NULL);
		}	break;

		default:
			break;
	}
}

//Ham tang do sang cua Led
static void Up_multiSensorScan(void *arg)
{
	 LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_WHITE,level);
	 level++;
}
//Ham giam do sang cua Led
static void Down_multiSensorScan(void *arg)
{
	 LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_WHITE,level);
	 level--;
}
//Ham tang do sang cua Led
static void Right_Up_LightScan(void *arg)
{
	 LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_RED,level_1);
	 level_1++;
}
//Ham giam do sang cua Led
static void Left_Down_LightScan(void *arg)
{
	 LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_RED,level_1);
	 level_1--;
}

//DELAY
void delay_ms(uint32_t milisecond)
{
	for(uint32_t i = 0; i < milisecond; i++){
		for(uint32_t j = 0; j < 1000 ; j++);
	}
}


//Ham do do am, do sang, nhiet do
static void Task_multiSensorScan(void *arg)
{
	temperature = (uint8_t)(TemHumSensor_GetTemp() / 100);
	humidity = (uint8_t)(TemHumSensor_GetHumi() / 100);
	light = LightSensor_MeasureUseDMAMode();

	//Display output

	//TEMPERATURE
	memset( src1, 0, sizeof(src1));
	sprintf(src1, "Temp = %d oC", temperature);
	ucg_DrawString(&ucg, 0, 45, 0, src1);
	TempSensor_SendPacketRespond(temperature);
	//HUMIDITY
	memset(src2, 0, sizeof(src2));
	sprintf(src2, "Humi = %d %%", humidity);
	ucg_DrawString(&ucg, 0, 70, 0, src2);
	HumiSensor_SendPacketRespond(humidity);
	//LIGHT
	memset(src3, 0, sizeof(src3));
	sprintf(src3, "Light = %d lux", light );
	ucg_DrawString(&ucg, 0, 97 , 0, src3);
	LightSensor_SendPacketRespond(light);
}

static void MultiSensorScan(void *arg)
{
	ucg_ClearScreen(&ucg);
	ucg_SetColor(&ucg, 0, 0, 255, 0);
	ucg_SetFont(&ucg, ucg_font_ncenR14_hf);
	//GET TIMER
	if(task_idMultiSensorScan != NO_TIMER)
	{
		TimerStop(task_idMultiSensorScan);
		task_idMultiSensorScan = NO_TIMER;
	}
	task_idMultiSensorScan = TimerStart("Task_multiSensorScan", 1000, TIMER_REPEAT_FOREVER , Task_multiSensorScan, NULL);
 }
















