/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <stm32f401re_gpio.h>
#include <stm32f401re_rcc.h>
#include <stm32f401re_usart.h>
#include <misc.h>
#include <stdbool.h>
/* Private macro */
/*----------------------------------------------------------------------------*/
#define GPIO_PIN_SET                1
#define GPIO_PIN_RESET              0

#define LED_GPIO_PORT				GPIOA
#define LED_GPIO_PIN				GPIO_Pin_1
#define LED_GPIO_RCC				RCC_AHB1Periph_GPIOA

#define BUTTON_GPIO_PORT            GPIOC
#define BUTTON_GPIO_PIN             GPIO_Pin_13
#define BUTTON_GPIO_RCC             RCC_AHB1Periph_GPIOC

#define USART6_TX_GPIO_PIN          GPIO_Pin_6
#define USART6_GPIO_PORT            GPIOC
#define USART6_GPIO_CLOCK           RCC_AHB1Periph_GPIOC
#define USART6_CLOCK                RCC_APB2Periph_USART6

#define USART1_RX_GPIO_PIN			GPIO_Pin_10
#define USART1_GPIO_PORT			GPIOA
#define USART1_GPIO_CLOCK			RCC_AHB1Periph_GPIOA
#define USART1_CLOCK				RCC_APB2Periph_USART1

#define DATA_TRANSMIT               0x10
#define DATA_RECEIVE				0x11

/* Private variables */
/*----------------------------------------------------------------------------*/
// Thêm biến này bên ngoài hàm main để lưu trạng thái trước đó của nút nhấn
static uint8_t lastButtonState = GPIO_PIN_SET; // Ban đầu coi như nút đang được thả (SET = 1)
uint8_t currentButtonState;
volatile uint8_t data_receive;
bool ledState = GPIO_PIN_RESET;
//LED
static void Led_Init(void)
{
	GPIO_InitTypeDef GPIO_InitStructure;
	RCC_AHB1PeriphClockCmd(LED_GPIO_RCC, ENABLE);
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;
	GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
	GPIO_InitStructure.GPIO_Pin = LED_GPIO_PIN;
	GPIO_Init(LED_GPIO_PORT, &GPIO_InitStructure);

}

static void Led_Control(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, uint8_t status)
{
	if( status == GPIO_PIN_SET)
	{
		GPIO_SetBits(GPIOx, GPIO_Pin);
	}
	else if( status == GPIO_PIN_RESET)
	{
		GPIO_ResetBits(GPIOx, GPIO_Pin);
	}
}
// BUTTON
static void Button_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStructure;

    RCC_AHB1PeriphClockCmd(BUTTON_GPIO_RCC, ENABLE);

    GPIO_InitStructure.GPIO_Mode = GPIO_Mode_IN;
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
    GPIO_InitStructure.GPIO_PuPd  = GPIO_PuPd_UP;
    GPIO_InitStructure.GPIO_Pin = BUTTON_GPIO_PIN;
    GPIO_Init(BUTTON_GPIO_PORT, &GPIO_InitStructure);
}


static uint8_t Button_GetLogic(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin)
{
	return GPIO_ReadInputDataBit(GPIOx, GPIO_Pin);
}

//MASTER
static void USART6_Init(void)
{

	GPIO_InitTypeDef		GPIO_InitStructure;
	USART_InitTypeDef		USART_InitStructure;
	//Enable Clock USART1 And GPIOC----------------------------------
	RCC_AHB1PeriphClockCmd(USART6_GPIO_CLOCK, ENABLE);

	//Initializes GPIO Use USART6 Peripheral---------------------
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AF;
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;
	GPIO_InitStructure.GPIO_Pin = USART6_TX_GPIO_PIN;
	GPIO_Init(USART6_GPIO_PORT, &GPIO_InitStructure);

	//Initializes GPIO As Alternate function mode-----------------
	GPIO_PinAFConfig(USART6_GPIO_PORT, GPIO_PinSource6, GPIO_AF_USART6);

	//Initializes USART6 Peripheral--------------------------
	RCC_APB2PeriphClockCmd(USART6_CLOCK, ENABLE);

	USART_InitStructure.USART_BaudRate = 9600;
	USART_InitStructure.USART_WordLength = USART_WordLength_8b;
	USART_InitStructure.USART_StopBits = USART_StopBits_1;
	USART_InitStructure.USART_Parity = USART_Parity_No;
	USART_InitStructure.USART_HardwareFlowControl = USART_HardwareFlowControl_None;
	USART_InitStructure.USART_Mode = USART_Mode_Tx;

	USART_Init(USART6, &USART_InitStructure);

	USART_Cmd(USART6, ENABLE);
}
//SLAVE
 static void USART1_Init(void)
 {
	 GPIO_InitTypeDef			GPIO_InitStructure;
	 USART_InitTypeDef			USART_InitStructure;
	 NVIC_InitTypeDef			NVIC_InitStructure;

	 //Cho phep dong ho tren chan PA10 chay
	 RCC_AHB1PeriphClockCmd(USART1_GPIO_CLOCK, ENABLE);
	 GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AF;
	 GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
	 GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;
	 GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
	 GPIO_InitStructure.GPIO_Pin = USART1_RX_GPIO_PIN;
	 GPIO_Init(USART1_GPIO_PORT, &GPIO_InitStructure);

	 //Chan thay the chan PA10 thanh che do UART
	 GPIO_PinAFConfig(USART1_GPIO_PORT, GPIO_PinSource10, GPIO_AF_USART1);
	 //Cap clock cho UART PA10
	 RCC_APB2PeriphClockCmd(USART1_CLOCK, ENABLE);
	 //Cau hinh chan PA10 o che do UART
	 USART_InitStructure.USART_BaudRate = 9600;
	 USART_InitStructure.USART_WordLength = USART_WordLength_8b;
	 USART_InitStructure.USART_StopBits = USART_StopBits_1;
	 USART_InitStructure.USART_Parity = USART_Parity_No;
	 USART_InitStructure.USART_HardwareFlowControl = USART_HardwareFlowControl_None;
	 USART_InitStructure.USART_Mode = USART_Mode_Rx;
	 USART_Init(USART1, &USART_InitStructure);
	 USART_Cmd(USART1, ENABLE);

	 //Cau hinh ngat tren chan PA10 UART
	 USART_ITConfig(USART1, USART_IT_RXNE, ENABLE );
	 NVIC_PriorityGroupConfig( NVIC_PriorityGroup_2);
	 //Cau hinh ngat
	 NVIC_InitStructure.NVIC_IRQChannel = USART1_IRQn;
	 NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;
	 NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 0;
	 NVIC_InitStructure.NVIC_IRQChannelSubPriority = 0;
	 NVIC_Init( &NVIC_InitStructure);
 }

void USART1_IRQHandler(void)
{
	if(USART_GetITStatus(USART1, USART_IT_RXNE) == SET)
	{
		data_receive = USART_ReceiveData(USART1);
	}
	USART_ClearITPendingBit(USART1, USART_IT_RXNE);
}
void AppInitCommon(void)
{
	SystemCoreClockUpdate();
	Led_Init();
	Button_Init();
	USART1_Init();
//	USART1_IRQHandler();
	USART6_Init();
}

void DelayMs(uint32_t ms)
{
	//loop forever
	for(uint32_t i = 0;i < ms ; i++)
	{
		for(uint32_t j = 0;j < 5000; j++);
	}
}

int main(void)
{
    AppInitCommon();

    while(1)
    {
    	//Transmit
        currentButtonState = Button_GetLogic(BUTTON_GPIO_PORT, BUTTON_GPIO_PIN);
        if ((currentButtonState == Bit_RESET) && (lastButtonState == Bit_SET))
        {
            // Gửi dữ liệu 0x10 qua USART6
            USART_SendData(USART6, DATA_TRANSMIT);
            DelayMs(300);
        }
        //Receive
        if( data_receive ==  DATA_RECEIVE)
        {
        	//Dao trang thai led
            	ledState = !ledState;

            	Led_Control(LED_GPIO_PORT, LED_GPIO_PIN, ledState);

        	data_receive = 0;
        }

    }
}
