/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
*/

#include <stdint.h>
#include <stdio.h>
#include <led.h>
#include <stm32f401re_gpio.h>
#include <stm32f401re_rcc.h>

// Macro
#define GPIO_PIN_SET 						1
#define GPIO_PIN_RESET						0


//LEDBLUE
#define LED_GPIO_PORT            			GPIOC
#define LED_GPIO_PIN             			GPIO_Pin_8
#define LED_GPIO_RCC 						RCC_AHB1Periph_GPIOC

//SENSOR
#define SENSOR_GPIO_PORT					GPIOA
#define SENSOR_GPIO_PIN						GPIO_Pin_1
#define SENSOR_GPIO_RCC						RCC_AHB1Periph_GPIOA

#define BUZZER_GPIO_PORT				    GPIOC
#define BUZZER_GPIO_PIN             	 	GPIO_Pin_9
#define BUZZER_GPIO_RCC						RCC_AHB1Periph_GPIOC


static void Led_Init(void)
{
	GPIO_InitTypeDef GPIO_InitStructure;

	// Cap xung clock cho led A
	RCC_AHB1PeriphClockCmd(LED_GPIO_RCC , ENABLE);

	GPIO_InitStructure.GPIO_Pin = LED_GPIO_PIN ;

	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;

	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;

	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;

	GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;

	GPIO_Init(LED_GPIO_PORT, &GPIO_InitStructure);
}

static void Motion_Sensor_Init(void)
{
	GPIO_InitTypeDef GPIO_InitStructure;

	// Cap xung clock cho sensor
	RCC_AHB1PeriphClockCmd(SENSOR_GPIO_RCC, ENABLE);

	GPIO_InitStructure.GPIO_Pin = SENSOR_GPIO_PIN;

	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_IN;

	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;

	GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;

	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;

	GPIO_Init(SENSOR_GPIO_PORT, &GPIO_InitStructure);
}

static void Buzzer_Init(void)
{
	GPIO_InitTypeDef GPIO_InitStructure;
	RCC_AHB1PeriphClockCmd(BUZZER_GPIO_RCC, ENABLE);
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_InitStructure.GPIO_Pin = BUZZER_GPIO_PIN;
	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;
	GPIO_Init(BUZZER_GPIO_PORT, &GPIO_InitStructure);
}

static void Led_Control(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, uint8_t status)
{
	if(status == GPIO_PIN_SET)
	{
		GPIO_SetBits(GPIOx, GPIO_Pin);
	}
	else if(status == GPIO_PIN_RESET)
	{
		GPIO_ResetBits(GPIOx, GPIO_Pin);
	}
}
static void Buzzer_Control(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, uint8_t status)
{
	if(status == GPIO_PIN_SET)
	{
		GPIO_SetBits(GPIOx, GPIO_Pin);
	}
	else if(status == GPIO_PIN_RESET)
	{
		GPIO_ResetBits(GPIOx, GPIO_Pin);
	}
}
void Delay_ms(uint32_t ms){
	//loop forever
	for(uint32_t i = 0; i < ms ; i++)
	{
		for(uint32_t j = 0;j < 5000; j++);
	}
}
static uint8_t Sensor_GetLogic(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin)
{
	return GPIO_ReadInputDataBit(GPIOx, GPIO_Pin);
}


int main(void)
{
	// System clock 84MHz ------------------------------------------------------
	SystemCoreClockUpdate();
	Led_Init();
	Buzzer_Init();
	Motion_Sensor_Init();
	int motion_detected_flag = 0;
	while(1)
	{

		if( Sensor_GetLogic(SENSOR_GPIO_PORT, SENSOR_GPIO_PIN) == 1)
		{
			Led_Control(LED_GPIO_PORT,LED_GPIO_PIN,1);
			Delay_ms(1000);
			if (motion_detected_flag == 0)
			{
				// Kêu còi một tiếng ngắn
				Buzzer_Control(BUZZER_GPIO_PORT, BUZZER_GPIO_PIN, 1); // Bật còi
				Delay_ms(500);                   // Giữ còi kêu trong khoảng thời gian ngắn
				Buzzer_Control(BUZZER_GPIO_PORT, BUZZER_GPIO_PIN, 0); // Tắt còi
				motion_detected_flag = 1;
			}
		}
		else if(Sensor_GetLogic(SENSOR_GPIO_PORT, SENSOR_GPIO_PIN) == 0)
		{
			Led_Control(LED_GPIO_PORT,LED_GPIO_PIN,0);
			Delay_ms(1000);
			motion_detected_flag = 0;
		}
	}
}


