/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f401re.h"
#include "i2c-lcd-baremetal-f4.h"

int main(void) {
    lcd_init();
    lcd_clear();
    lcd_set_cursor(0, 1);
    lcd_send_string("Hello World!");

//
    lcd_set_cursor(1, 1);
    lcd_send_string("Bare-metal I2C");

    while (1) {

    }
}
