/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "led.h"
#include "time.h"

void delay_ms(uint32_t milisecond);

int main(void)
{
	LedControl_Init();
    /* Loop forever */
	while(1)
	{
		LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_RED, 100);
		//bat den tren kit 0 mau xanh la
		LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_GREEN, 100);
		delay_ms(5000); //do tre
		//bat den tren kit 0 mau vang
		LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_YELLOW, 100);
		delay_ms(2000); //do tre
		///
		///
		LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_RED, 100);
		//bat den tren kit 1 mau xanh la
		LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_GREEN, 100);
		delay_ms(5000); //do tre
		//bat den tren kit 1 mau vang
		LedControl_SetColorGeneral(LED_KIT_ID1, LED_COLOR_YELLOW, 100);
		delay_ms(2000); //do tre
	}

}


void delay_ms(uint32_t milisecond)
{
	//loop forever
	for(uint32_t i = 0; i < milisecond ; i++)
	{
		for(uint32_t j = 0; j < 5000; j++);
	}
}
