/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>
#include <stdio.h>
#include <stm32f401re_rcc.h>
#include <stm32f401re_gpio.h>
#include <stm32f401re_tim.h>
#include <stdbool.h>
#define GPIO_PIN_SET			1
#define GPIO_PIN_RESET			0

#define LED_GPIO_PORT 			GPIOC
#define LED_GPIO_PIN			GPIO_Pin_8   //LED BLUE PC8
#define LED_GPIO_RCC			RCC_AHB1Periph_GPIOC

#define SOUND_GPIO_PORT			GPIOA
#define SOUND_GPIO_PIN			GPIO_Pin_0
#define SOUND_GPIO_RCC			RCC_AHB1Periph_GPIOA


static void TimeBasic_Init(void)
{
	TIM_TimeBaseInitTypeDef	Timer_InitStructure;

	RCC_APB2PeriphClockCmd(RCC_APB2Periph_TIM1, ENABLE);
	//Cau hinh Timer
	Timer_InitStructure.TIM_CounterMode = TIM_CounterMode_Up;
	Timer_InitStructure.TIM_Prescaler = 83;
	Timer_InitStructure.TIM_Period = 999;
	Timer_InitStructure.TIM_ClockDivision = TIM_CKD_DIV1;
	Timer_InitStructure.TIM_RepetitionCounter = 0;
	TIM_TimeBaseInit(TIM1, &Timer_InitStructure);

	TIM_Cmd(TIM1, ENABLE);
}
static void Led_Init(void)
{
	GPIO_InitTypeDef GPIO_InitStructure;

	RCC_AHB1PeriphClockCmd(LED_GPIO_RCC, ENABLE);
	//Cau hinh chan GPIO A Pin 1
	GPIO_InitStructure.GPIO_Pin = LED_GPIO_PIN;

	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;

	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;

	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;

	GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;

	GPIO_Init(LED_GPIO_PORT, &GPIO_InitStructure);
}

static void Sound_Sensor_Init(void)
{
	GPIO_InitTypeDef GPIO_InitStructure;
	RCC_AHB1PeriphClockCmd(SOUND_GPIO_RCC, ENABLE);
	//Cau hinh chan GPIO A Pin 0 cho cam bien am thanh
	GPIO_InitStructure.GPIO_Pin = SOUND_GPIO_PIN;

	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;

	GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;

	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;

	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_IN;

	GPIO_Init(SOUND_GPIO_PORT, &GPIO_InitStructure);
}

static void Led_Control(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, uint8_t status)
{
	if(status == GPIO_PIN_SET)
	{
		GPIO_SetBits( GPIOx, GPIO_Pin);
	}else if(status == GPIO_PIN_RESET)
	{
		GPIO_ResetBits( GPIOx, GPIO_Pin);
	}
}

static uint8_t Sound_Sensor_GetLogic(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin)
{
	return GPIO_ReadInputDataBit(GPIOx, GPIO_Pin);
}

void Delay_ms(uint32_t ms)
{
	while(ms != 0)
	{
		TIM_SetCounter(TIM1, 0);
		while(TIM_GetCounter(TIM1) != 999);
		ms--;
	}
}

bool statusLed = false;

int main(void)
{
	SystemCoreClockUpdate();
	TimeBasic_Init();
	Led_Init();
	Sound_Sensor_Init();

//  Loop forever
	while(1)
	{
		//Den khong sang va co tin hieu am thanh -> bat den
		if( Sound_Sensor_GetLogic(SOUND_GPIO_PORT, SOUND_GPIO_PIN) == 1)
		{
			if( statusLed == false)
			{
				Led_Control(LED_GPIO_PORT, LED_GPIO_PIN, GPIO_PIN_SET);
				Delay_ms(1000);
				statusLed = true;
			}else
			{
				Led_Control(LED_GPIO_PORT, LED_GPIO_PIN, GPIO_PIN_RESET);
				Delay_ms(1000);
				statusLed = false;
			}
			Delay_ms(200);
		}

/*		//Den dang sang va co tin hieu am thanh -> tat den
*/
	}

}

